name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.1", "8.2", "8.3", "8.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          extensions: bcmath
          tools: composer

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-composer-

      - name: Validate Composer configuration
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Check coding standards
        run: composer run -- cs

      - name: Static analysis
        run: composer run -- analyse

      - name: Run tests
        run: composer run -- test

      - name: Run tests with coverage
        run: composer run -- test-coverage

      - name: Coverage regression check
        run: |
          if [ ! -f build/coverage/clover.xml ]; then
            echo "Coverage report not found" >&2
            exit 1
          fi
          php bin/check-coverage.php build/coverage/clover.xml 90

      - name: Mutation testing
        run: composer run -- mutation

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-php-${{ matrix.php-version }}
          path: |
            build/coverage
            build/infection
          if-no-files-found: warn

      - name: Security audit
        run: composer audit --locked
